repos:
- repo: local
  hooks:
  - id: cargo-fmt
    name: cargo fmt
    description: Format Rust code using rustfmt
    entry: cargo +nightly fmt --
    language: system
    types:
    - rust
    pass_filenames: false

# sigil 12ca70ed877e1bce091b2a624db49eb2
# template-meta template-version=1.8.7
# template-meta zuper-templating-version=8.25.2901010000
