[package]
name = "mcdp-format2-rs"
version = "2.19.1"
edition = "2024"
include = ["src/**/*", "Cargo.toml"]

description = "A Rust library for loading and saving datasets in the MCDP V2 format."
license = "Apache-2.0 OR MIT"

[dependencies]
anyhow = { version = "1", features = ["std"], default-features = false }
ciborium = { version = "0.2.2", default-features = false,  features = ["default"]}
clap = { version = "4.5", features = ["derive", "help", "std", "color", "usage", "error-context", "suggestions"], default-features = false }
flate2 = { version = "1.1.2", features = ["zlib"], default-features = false }
glob = { version = "0.3", default-features = false }
serde = { version = "1.0", features = ["derive"], default-features = false }
serde_json = { version = "1.0", features = ["preserve_order", "std"], default-features = false }
serde_yaml = { version = "0.9", default-features = false }
walkdir = { version = "2", default-features = false }


[lib]
path = "src/lib.rs"
name = "mcdp_format2_rs"
crate-type = ["lib"]
required-features = []

[[bin]]
path = "src/main.rs"
name = "mcdp-format2-rs-load"
required-features = []


[dev-dependencies]
datatest-stable = "0.3"


[features]
default = []



[[test]]
name = "datasets"
harness = false
